//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-13
//     Last Modified: 2024-12-13
//     Description: 
//       Defines a specification for filtering a OfferLine entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.OfferLines.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering OfferLines by their ID.
/// </summary>
public class OfferLineByIdSpecification : Specification<OfferLine>
{
    public OfferLineByIdSpecification(int id)
    {
       Query.Where(q => q.OfferId == id);
    }
}