//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       This file defines the validation rules for the UpdateCrmProductCategoryCommand within 
//       the CleanArchitecture.Blazor application. It ensures that the command has 
//       all required fields properly populated and validates constraints such as 
//       maximum length and non-null requirements before proceeding with updating 
//       a crmproductcategory.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/crmproductcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `UpdateCrmProductCategoryCommandValidator` is used to validate that an `UpdateCrmProductCategoryCommand` 
// contains valid and complete data before processing the update. It enforces rules such as 
// ensuring that the `Id` is provided, the `Name` is not empty, and certain properties 
// (e.g., ...) do not exceed their maximum 
// allowed length.

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.Update;

public class UpdateCrmProductCategoryCommandValidator : AbstractValidator<UpdateCrmProductCategoryCommand>
{
        public UpdateCrmProductCategoryCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.CategoryName).MaximumLength(255); 
    RuleFor(v => v.CrmProductId).NotNull(); 

          
        }
    
}

