//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the Offer entity 
//       used within the CleanArchitecture.Blazor application. The OfferDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offer
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `OfferDto` class is used to represent offer data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing offer information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.OfferLines.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Offers.DTOs;

[Description("Offers")]
public class OfferDto
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Customer id")]
    public int CustomerId {get;set;} 
    [Description("Offer date")]
    public DateTime OfferDate {get;set;} 
    [Description("Total amount")]
    public decimal TotalAmount {get;set;} 
    [Description("Status")]
    public string? Status {get;set;}

    [Description("Offer lines")]
    public List<OfferLineDto>? OfferLines { get; set; }

    [Description("Customer")]
    public int ContactDto { get; set; }


}

