//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-07-18
// Handles ContactDeletedEvent: triggered when a contact is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Contacts.EventHandlers;

    public class ContactDeletedEventHandler : INotificationHandler<ContactDeletedEvent>
    {
        private readonly ILogger<ContactDeletedEventHandler> _logger;

        public ContactDeletedEventHandler(
            ILogger<ContactDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ContactDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
