//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-07
//     Last Modified: 2024-12-07
//     Description: 
//       This file defines the command and its handler for deleting one or more
//       OfferLine entities from the CleanArchitecture.Blazor application. It
//       implements caching invalidation logic to ensure that data consistency is
//       maintained. Domain events are triggered for deleted entities to support 
//       integration with other parts of the system.
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offerline
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to delete multiple OfferLines from the system by specifying
// their IDs. The handler also raises domain events for each deleted offerline to
// notify other bounded contexts and invalidate relevant cache entries.

using CleanArchitecture.Blazor.Application.Features.OfferLines.Caching;


namespace CleanArchitecture.Blazor.Application.Features.OfferLines.Commands.Delete;

public class DeleteOfferLineCommand:  ICacheInvalidatorRequest<Result<int>>
{
  public int[] Id {  get; }
  public string CacheKey => OfferLineCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => OfferLineCacheKey.Tags;
  public DeleteOfferLineCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteOfferLineCommandHandler : 
             IRequestHandler<DeleteOfferLineCommand, Result<int>>

{
    private readonly IApplicationDbContext _context;
    public DeleteOfferLineCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(DeleteOfferLineCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.OfferLines.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			//item.AddDomainEvent(new OfferLineDeletedEvent(item));
            _context.OfferLines.Remove(item);
        }
        var result = await _context.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(result);
    }

}

