//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-13
//     Last Modified: 2024-12-13
//     Description: 
//       This file defines the command and its handler for creating a new OfferLine entity
//       within the CleanArchitecture.Blazor application. The command uses caching
//       invalidation to ensure data consistency and raises domain events to maintain 
//       the integrity of the entity lifecycle. It leverages Clean Architecture principles 
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offerline
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to create a new offerline entity in the system. It includes
// the required fields for the offerline and automatically raises necessary domain
// events for integration with other bounded contexts in the application.

using CleanArchitecture.Blazor.Application.Features.OfferLines.Caching;
using CleanArchitecture.Blazor.Application.Features.OfferLines.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.OfferLines.Commands.Create;

public class CreateOfferLineCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Offer id")]
    public int OfferId {get;set;} 
    [Description("Item id")]
    public int ItemId {get;set;} 
    [Description("Quantity")]
    public int Quantity {get;set;} 
    [Description("Discount")]
    public decimal Discount {get;set;} 
    [Description("Line total")]
    public decimal LineTotal {get;set;} 

      public string CacheKey => OfferLineCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => OfferLineCacheKey.Tags;
}
    
    public class CreateOfferLineCommandHandler : IRequestHandler<CreateOfferLineCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        public CreateOfferLineCommandHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<Result<int>> Handle(CreateOfferLineCommand request, CancellationToken cancellationToken)
        {
        //   var item = OfferLineMapper.FromCreateCommand(request);
        //   // raise a create domain event
	       //item.AddDomainEvent(new OfferLineCreatedEvent(item));
        //   _context.OfferLines.Add(item);
        //   await _context.SaveChangesAsync(cancellationToken);
        //   return  await Result<int>.SuccessAsync(item.Id);

        return await Result<int>.SuccessAsync(0);
         }
    }

