//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Resources.Common.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterFormModelFluentValidator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterFormModelFluentValidator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitecture.Blazor.Application.Resources.Common.Security.RegisterFormModelF" +
                            "luentValidator", typeof(RegisterFormModelFluentValidator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be empty.
        /// </summary>
        internal static string Your_password_cannot_be_empty {
            get {
                return ResourceManager.GetString("Your password cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password length must be at least 6..
        /// </summary>
        internal static string Your_password_length_must_be_at_least_6_ {
            get {
                return ResourceManager.GetString("Your password length must be at least 6.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password length must not exceed 16..
        /// </summary>
        internal static string Your_password_length_must_not_exceed_16_ {
            get {
                return ResourceManager.GetString("Your password length must not exceed 16.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one (@!? *.)..
        /// </summary>
        internal static string Your_password_must_contain_at_least_one__________ {
            get {
                return ResourceManager.GetString("Your password must contain at least one (@!? *.).", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one lowercase letter..
        /// </summary>
        internal static string Your_password_must_contain_at_least_one_lowercase_letter_ {
            get {
                return ResourceManager.GetString("Your password must contain at least one lowercase letter.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one number..
        /// </summary>
        internal static string Your_password_must_contain_at_least_one_number_ {
            get {
                return ResourceManager.GetString("Your password must contain at least one number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least one uppercase letter..
        /// </summary>
        internal static string Your_password_must_contain_at_least_one_uppercase_letter_ {
            get {
                return ResourceManager.GetString("Your password must contain at least one uppercase letter.", resourceCulture);
            }
        }
    }
}
