//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       This file defines the validation rules for the AddEditSubProductCommand 
//       used to add or edit SubProduct entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subproduct
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditSubProductCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Commands.AddEdit;

public class AddEditSubProductCommandValidator : AbstractValidator<AddEditSubProductCommand>
{
    public AddEditSubProductCommandValidator()
    {
        RuleFor(v => v.Unit).MaximumLength(255); 
        RuleFor(v => v.Color).MaximumLength(255); 

     }

}

