//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-19
//     Last Modified: 2024-12-19
//     Description: 
//       This file defines the validation rules for the ImportInvoicesCommand 
//       within the CleanArchitecture.Blazor application. It ensures that the 
//       command's required properties are correctly set before proceeding with 
//       the invoice import process.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/invoice
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator is used to ensure that an ImportInvoicesCommand has valid input 
// before attempting to import invoice data. It checks that the Data property is not 
// null and is not empty, ensuring that the command has valid content for import.

using CleanArchitecture.Blazor.Application.Features.Invoices.Commands.Import;

namespace CleanArchitecture.Blazor.Application.Invoices.Commands.Import;

public class ImportInvoicesCommandValidator : AbstractValidator<ImportInvoicesCommand>
{
        public ImportInvoicesCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

