//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       This file defines the validation rules for the CreateSubProductCommand, 
//       used to create SubProduct entities within the CleanArchitecture.Blazor 
//       application. It ensures that essential fields are validated correctly, 
//       including maximum lengths and mandatory requirements for required fields.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subproduct
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator is used to ensure that a CreateSubProductCommand meets the required
// validation criteria. It enforces constraints like maximum field lengths and 
// ensures that the Name field is not empty before proceeding with the command execution.

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Commands.Create;

public class CreateSubProductCommandValidator : AbstractValidator<CreateSubProductCommand>
{
        public CreateSubProductCommandValidator()
        {
                RuleFor(v => v.ProdId).NotNull(); 
    RuleFor(v => v.Unit).MaximumLength(255); 
    RuleFor(v => v.Color).MaximumLength(255); 

        }
       
}

