//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       subproducts from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a subproduct template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subproduct
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportSubProductsCommand` to import subproducts from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateSubProductsTemplateCommand` to generate an Excel template for entering subproduct data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.SubProducts.DTOs;
using CleanArchitecture.Blazor.Application.Features.SubProducts.Caching;
using CleanArchitecture.Blazor.Application.Features.SubProducts.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Commands.Import;

    public class ImportSubProductsCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => SubProductCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => SubProductCacheKey.Tags;
        public ImportSubProductsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateSubProductsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportSubProductsCommandHandler : 
                 IRequestHandler<CreateSubProductsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportSubProductsCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportSubProductsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly SubProductDto _dto = new();

        public ImportSubProductsCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportSubProductsCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportSubProductsCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, SubProductDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.ProductId)], (row, item) => item.ProductId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ProductId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Unit)], (row, item) => item.Unit = row[_localizer[_dto.GetMemberDescription(x=>x.Unit)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Color)], (row, item) => item.Color = row[_localizer[_dto.GetMemberDescription(x=>x.Color)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
            //        var exists = await _context.SubProducts.AnyAsync(x => x.Name == dto.\\\\, cancellationToken);
            //        if (!exists)
            //        {
            //            var item = SubProductMapper.FromDto(dto);
            //            // add create domain events if this entity implement the IHasDomainEvent interface
				        //// item.AddDomainEvent(new SubProductCreatedEvent(item));
            //            await _context.SubProducts.AddAsync(item, cancellationToken);
            //        }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateSubProductsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportSubProductsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.ProductId)], 
_localizer[_dto.GetMemberDescription(x=>x.Unit)], 
_localizer[_dto.GetMemberDescription(x=>x.Color)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

