//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Configures the properties and behaviors for the `CrmProductCategory` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class CrmProductCategoryConfiguration : IEntityTypeConfiguration<CrmProductCategory>
{
    public void Configure(EntityTypeBuilder<CrmProductCategory> builder)
    {
        builder.Property(x => x.CategoryName).HasMaxLength(255); 

        builder.Ignore(e => e.DomainEvents);
    }
}


