//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-07
//     Last Modified: 2024-12-07
//     Description: 
//       Configures the properties and behaviors for the `OfferLine` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class OfferLineConfiguration : IEntityTypeConfiguration<OfferLine>
{
    public void Configure(EntityTypeBuilder<OfferLine> builder)
    {
            builder.HasOne(x => x.Offer).WithMany().HasForeignKey(x => x.OfferId); 

        builder.Ignore(e => e.DomainEvents);
    }
}


