//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       Configures the properties and behaviors for the `SubProduct` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class SubProductConfiguration : IEntityTypeConfiguration<SubProduct>
{
    public void Configure(EntityTypeBuilder<SubProduct> builder)
    {

        builder.ToTable("SubProduct");
        builder.HasIndex(x => x.ProductId);

        builder.Property(x => x.Unit).HasMaxLength(450); 
        builder.Property(x => x.Color).HasMaxLength(450);

        builder.Property(sp => sp.Price)
                    .HasColumnType("decimal(18,2)");

        builder.Property(sp => sp.RetailPrice)
                    .HasColumnType("decimal(18,2)");

        builder.HasOne(d => d.Product).WithMany(p => p.SubProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull);

        builder.Ignore(e => e.DomainEvents);
    }
}


