//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       offers from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a offer template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offer
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportOffersCommand` to import offers from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateOffersTemplateCommand` to generate an Excel template for entering offer data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.Offers.DTOs;
using CleanArchitecture.Blazor.Application.Features.Offers.Caching;
using CleanArchitecture.Blazor.Application.Features.Offers.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Offers.Commands.Import;

    public class ImportOffersCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => OfferCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => OfferCacheKey.Tags;
        public ImportOffersCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateOffersTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportOffersCommandHandler : 
                 IRequestHandler<CreateOffersTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportOffersCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportOffersCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly OfferDto _dto = new();

        public ImportOffersCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportOffersCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportOffersCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, OfferDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.CustomerId)], (row, item) => item.CustomerId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.CustomerId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.OfferDate)], (row, item) => item.OfferDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.OfferDate)]].ToString()) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.TotalAmount)], (row, item) => item.TotalAmount =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.TotalAmount)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Status)], (row, item) => item.Status = row[_localizer[_dto.GetMemberDescription(x=>x.Status)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.Offers.AnyAsync(x => x.Id == dto.Id, cancellationToken);
                    if (!exists)
                    {
                        var item = OfferMapper.FromDto(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new OfferCreatedEvent(item));
                        await _context.Offers.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateOffersTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportOffersCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.CustomerId)], 
_localizer[_dto.GetMemberDescription(x=>x.OfferDate)], 
_localizer[_dto.GetMemberDescription(x=>x.TotalAmount)], 
_localizer[_dto.GetMemberDescription(x=>x.Status)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

