//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Defines a query for retrieving crmproductcategorys with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.DTOs;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Caching;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Mappers;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Queries.Pagination;

public class CrmProductCategoriesWithPaginationQuery : CrmProductCategoryAdvancedFilter, ICacheableRequest<PaginatedData<CrmProductCategoryDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => CrmProductCategoryCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => CrmProductCategoryCacheKey.Tags;
    public CrmProductCategoryAdvancedSpecification Specification => new CrmProductCategoryAdvancedSpecification(this);
}
    
public class CrmProductCategoriesWithPaginationQueryHandler :
         IRequestHandler<CrmProductCategoriesWithPaginationQuery, PaginatedData<CrmProductCategoryDto>>
{
        private readonly IApplicationDbContext _context;

        public CrmProductCategoriesWithPaginationQueryHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<PaginatedData<CrmProductCategoryDto>> Handle(CrmProductCategoriesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.CrmProductCategories.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync(request.Specification, 
                                                                                request.PageNumber, 
                                                                                request.PageSize, 
                                                                                CrmProductCategoryMapper.ToDto, 
                                                                                cancellationToken);
            return data;
        }
}