//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the UpdateSupplierCommand and its handler for updating 
//       an existing Supplier entity within the CleanArchitecture.Blazor application. 
//       It includes caching invalidation logic to maintain data consistency and 
//       raises a domain event upon successful update to notify other parts of the system.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/supplier
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// Use `UpdateSupplierCommand` to update an existing supplier entity in the system. 
// The handler ensures that if the entity is found, the changes are applied and 
// the necessary domain event (`SupplierUpdatedEvent`) is raised. Caching is also 
// invalidated to keep the supplier list consistent.

using CleanArchitecture.Blazor.Application.Features.Suppliers.Caching;
using CleanArchitecture.Blazor.Application.Features.Suppliers.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Suppliers.Commands.Update;

public class UpdateSupplierCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
            [Description("Name")]
    public string Name {get;set;} 
    [Description("Address")]
    public string? Address {get;set;} 
    [Description("Phone")]
    public string? Phone {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Vat")]
    public string? VAT {get;set;} 
    [Description("Country")]
    public string? Country {get;set;} 
    [Description("Created at")]
    public DateTime CreatedAt {get;set;} 

      public string CacheKey => SupplierCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => SupplierCacheKey.Tags;

}

public class UpdateSupplierCommandHandler : IRequestHandler<UpdateSupplierCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public UpdateSupplierCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(UpdateSupplierCommand request, CancellationToken cancellationToken)
    {

       var item = await _context.Suppliers.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"Supplier with id: [{request.Id}] not found.");
       }
       SupplierMapper.ApplyChangesFrom(request, item);
	    // raise a update domain event
	   item.AddDomainEvent(new SupplierUpdatedEvent(item));
       await _context.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

