//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Defines permission constants for category-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("Category Permissions")]
    [Description("Set permissions for category operations.")]
    public static class Categories
    {
        [Description("Allows viewing category details.")]
        public const string View = "Permissions.Categories.View";
        [Description("Allows creating category details.")]
        public const string Create = "Permissions.Categories.Create";
        [Description("Allows editing category details.")]
        public const string Edit = "Permissions.Categories.Edit";
        [Description("Allows deleting category details.")]
        public const string Delete = "Permissions.Categories.Delete";
        [Description("Allows printing category details.")]
        public const string Print = "Permissions.Categories.Print";
        [Description("Allows searching category details.")]
        public const string Search = "Permissions.Categories.Search";
        [Description("Allows exporting category details.")]
        public const string Export = "Permissions.Categories.Export";
        [Description("Allows importing category details.")]
        public const string Import = "Permissions.Categories.Import";
    }
}

