//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       Defines permission constants for offer-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("Offer Permissions")]
    [Description("Set permissions for offer operations.")]
    public static class Offers
    {
        [Description("Allows viewing offer details.")]
        public const string View = "Permissions.Offers.View";
        [Description("Allows creating offer details.")]
        public const string Create = "Permissions.Offers.Create";
        [Description("Allows editing offer details.")]
        public const string Edit = "Permissions.Offers.Edit";
        [Description("Allows deleting offer details.")]
        public const string Delete = "Permissions.Offers.Delete";
        [Description("Allows printing offer details.")]
        public const string Print = "Permissions.Offers.Print";
        [Description("Allows searching offer details.")]
        public const string Search = "Permissions.Offers.Search";
        [Description("Allows exporting offer details.")]
        public const string Export = "Permissions.Offers.Export";
        [Description("Allows importing offer details.")]
        public const string Import = "Permissions.Offers.Import";
    }
}

