//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       Defines permission constants for subproduct-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("SubProduct Permissions")]
    [Description("Set permissions for subproduct operations.")]
    public static class SubProducts
    {
        [Description("Allows viewing subproduct details.")]
        public const string View = "Permissions.SubProducts.View";
        [Description("Allows creating subproduct details.")]
        public const string Create = "Permissions.SubProducts.Create";
        [Description("Allows editing subproduct details.")]
        public const string Edit = "Permissions.SubProducts.Edit";
        [Description("Allows deleting subproduct details.")]
        public const string Delete = "Permissions.SubProducts.Delete";
        [Description("Allows printing subproduct details.")]
        public const string Print = "Permissions.SubProducts.Print";
        [Description("Allows searching subproduct details.")]
        public const string Search = "Permissions.SubProducts.Search";
        [Description("Allows exporting subproduct details.")]
        public const string Export = "Permissions.SubProducts.Export";
        [Description("Allows importing subproduct details.")]
        public const string Import = "Permissions.SubProducts.Import";
    }
}

