//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-16
//     Last Modified: 2024-12-16
//     Description: 
//       Defines permission constants for supplyitem-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("SupplyItem Permissions")]
    [Description("Set permissions for supplyitem operations.")]
    public static class SupplyItems
    {
        [Description("Allows viewing supplyitem details.")]
        public const string View = "Permissions.SupplyItems.View";
        [Description("Allows creating supplyitem details.")]
        public const string Create = "Permissions.SupplyItems.Create";
        [Description("Allows editing supplyitem details.")]
        public const string Edit = "Permissions.SupplyItems.Edit";
        [Description("Allows deleting supplyitem details.")]
        public const string Delete = "Permissions.SupplyItems.Delete";
        [Description("Allows printing supplyitem details.")]
        public const string Print = "Permissions.SupplyItems.Print";
        [Description("Allows searching supplyitem details.")]
        public const string Search = "Permissions.SupplyItems.Search";
        [Description("Allows exporting supplyitem details.")]
        public const string Export = "Permissions.SupplyItems.Export";
        [Description("Allows importing supplyitem details.")]
        public const string Import = "Permissions.SupplyItems.Import";
    }
}

