//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       Defines permission constants for supplier-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("Supplier Permissions")]
    [Description("Set permissions for supplier operations.")]
    public static class Suppliers
    {
        [Description("Allows viewing supplier details.")]
        public const string View = "Permissions.Suppliers.View";
        [Description("Allows creating supplier details.")]
        public const string Create = "Permissions.Suppliers.Create";
        [Description("Allows editing supplier details.")]
        public const string Edit = "Permissions.Suppliers.Edit";
        [Description("Allows deleting supplier details.")]
        public const string Delete = "Permissions.Suppliers.Delete";
        [Description("Allows printing supplier details.")]
        public const string Print = "Permissions.Suppliers.Print";
        [Description("Allows searching supplier details.")]
        public const string Search = "Permissions.Suppliers.Search";
        [Description("Allows exporting supplier details.")]
        public const string Export = "Permissions.Suppliers.Export";
        [Description("Allows importing supplier details.")]
        public const string Import = "Permissions.Suppliers.Import";
    }
}

