//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2026-04-01
// ContactDto: transfers contact data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using System.ComponentModel.DataAnnotations;
namespace CleanArchitecture.Blazor.Application.Features.Contacts.DTOs;

[Description("Contacts")]
public class ContactDto
{
    [Display(Name ="Id")]
    public int Id { get; set; }
        [Display(Name = "Name")]
    public string Name {get;set;} 
    [Display(Name = "Description")]
    public string? Description {get;set;} 
    [Display(Name = "Email")]
    public string? Email {get;set;} 
    [Display(Name = "Phone number")]
    public string? PhoneNumber {get;set;} 
    [Display(Name = "Country")]
    public string? Country {get;set;} 

    [Display(Name = "Created By")]
    public UserBriefDto? CreatedBy { get; set; }
    [Display(Name = "Last Modified By")]
    public UserBriefDto? LastModifiedBy { get; set; }
    [Display(Name = "Created At")]
    public DateTime? CreatedAt { get; set; }
    [Display(Name = "Last Modified At")]
    public DateTime? LastModifiedAt { get; set; }
    
}

