//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       Defines a query to retrieve a offer by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same offer.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Offers.DTOs;
using CleanArchitecture.Blazor.Application.Features.Offers.Caching;
using CleanArchitecture.Blazor.Application.Features.Offers.Mappers;
using CleanArchitecture.Blazor.Application.Features.Offers.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Offers.Queries.GetById;

public class GetOfferByIdQuery : ICacheableRequest<Result<OfferDto>>
{
   public required int Id { get; set; }
   public string CacheKey => OfferCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => OfferCacheKey.Tags;
}

public class GetOfferByIdQueryHandler :
     IRequestHandler<GetOfferByIdQuery, Result<OfferDto>>
{
    private readonly IApplicationDbContext _context;

    public GetOfferByIdQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<OfferDto>> Handle(GetOfferByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Offers.ApplySpecification(new OfferByIdSpecification(request.Id))
                                                .ProjectTo()
                                                .FirstAsync(cancellationToken);
        return await Result<OfferDto>.SuccessAsync(data);
    }
}
