//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2026-04-01
// Validator for ImportContactsCommand: ensures the Data property is non-null and non-empty for contact import.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Contacts.Commands.Import;

public class ImportContactsCommandValidator : AbstractValidator<ImportContactsCommand>
{
        public ImportContactsCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

