//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2026-04-01
// Import command & template for contacts.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using System.ComponentModel.DataAnnotations;
using CleanArchitecture.Blazor.Application.Features.Contacts.DTOs;
using CleanArchitecture.Blazor.Application.Features.Contacts.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Contacts.Commands.Import;

    public class ImportContactsCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => ContactCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => ContactCacheKey.Tags;
        public ImportContactsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateContactsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportContactsCommandHandler : 
                 IRequestHandler<CreateContactsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportContactsCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportContactsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly ContactDto _dto = new();
        private readonly IObjectMapper _objectMapper;
        public ImportContactsCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IObjectMapper objectMapper,
            IExcelService excelService,
            IStringLocalizer<ImportContactsCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _objectMapper = objectMapper;
        }
        #nullable disable warnings
        public async ValueTask<Result<int>> Handle(ImportContactsCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, ContactDto, object?>>
            {
                                { _localizer[_dto.GetMemberDisplayName(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDisplayName(x=>x.Name)]].ToString() }, 
                { _localizer[_dto.GetMemberDisplayName(x=>x.Description)], (row, item) => item.Description = row[_localizer[_dto.GetMemberDisplayName(x=>x.Description)]].ToString() }, 
                { _localizer[_dto.GetMemberDisplayName(x=>x.Email)], (row, item) => item.Email = row[_localizer[_dto.GetMemberDisplayName(x=>x.Email)]].ToString() }, 
                { _localizer[_dto.GetMemberDisplayName(x=>x.PhoneNumber)], (row, item) => item.PhoneNumber = row[_localizer[_dto.GetMemberDisplayName(x=>x.PhoneNumber)]].ToString() }, 
                { _localizer[_dto.GetMemberDisplayName(x=>x.Country)], (row, item) => item.Country = row[_localizer[_dto.GetMemberDisplayName(x=>x.Country)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Contacts.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _objectMapper.Map<Contact>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new ContactCreatedEvent(item));
                        await db.Contacts.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async ValueTask<Result<byte[]>> Handle(CreateContactsTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDisplayName(x=>x.Name)], 
_localizer[_dto.GetMemberDisplayName(x=>x.Description)], 
_localizer[_dto.GetMemberDisplayName(x=>x.Email)], 
_localizer[_dto.GetMemberDisplayName(x=>x.PhoneNumber)], 
_localizer[_dto.GetMemberDisplayName(x=>x.Country)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

