//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the validation rules for the CreateOfferCommand, 
//       used to create Offer entities within the CleanArchitecture.Blazor 
//       application. It ensures that essential fields are validated correctly, 
//       including maximum lengths and mandatory requirements for required fields.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offer
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator is used to ensure that a CreateOfferCommand meets the required
// validation criteria. It enforces constraints like maximum field lengths and 
// ensures that the Name field is not empty before proceeding with the command execution.

namespace CleanArchitecture.Blazor.Application.Features.Offers.Commands.Create;

public class CreateOfferCommandValidator : AbstractValidator<CreateOfferCommand>
{
        public CreateOfferCommandValidator()
        {
                RuleFor(v => v.CustomerId).NotNull(); 
    RuleFor(v => v.OfferDate).NotNull(); 
    RuleFor(v => v.TotalAmount).NotNull(); 
    RuleFor(v => v.Status).MaximumLength(255); 

        }
       
}

