//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the SubProduct entity 
//       used within the CleanArchitecture.Blazor application. The SubProductDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subproduct
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `SubProductDto` class is used to represent subproduct data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing subproduct information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.Products.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.DTOs;

[Description("SubProducts")]
public class SubProductDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Prod id")]
    public int ProdId {get;set;} 
    [Description("Unit")]
    public string? Unit {get;set;} 
    [Description("Color")]
    public string? Color {get;set;} 
    [Description("Product")]
    public ProductDto Product {get;set;} 


}

