global using System.Data;
global using AutoMapper.QueryableExtensions;
global using CleanArchitecture.Blazor.Application.Common.Interfaces;
global using CleanArchitecture.Blazor.Application.Common.Models;
global using CleanArchitecture.Blazor.Infrastructure.Extensions;
global using CleanArchitecture.Blazor.Domain.Entities;
global using CleanArchitecture.Blazor.Server.UI.Components;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Microsoft.EntityFrameworkCore;
global using Severity = MudBlazor.Severity;