//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     CreatedAt Date: 2025-07-18
//     Last Modified: 2025-07-18
//     Description: 
//       Defines a specification for filtering a Contact entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Contacts.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering Contacts by their ID.
/// </summary>
public class ContactByIdSpecification : Specification<Contact>
{
    public ContactByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}
