//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for SubProduct-related data. This includes creating unique cache keys for 
//       various subproduct queries (such as getting all subproducts, subproducts by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for SubProduct-related data.
/// </summary>
public static class SubProductCacheKey
{
    public const string GetAllCacheKey = "all-SubProducts";
    public static string GetPaginationCacheKey(string parameters) {
        return $"SubProductCacheKey:SubProductsWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"SubProductCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"SubProductCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"SubProductCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "subproduct" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

