//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       This file defines the validation rules for the CreateCrmProductCategoryCommand, 
//       used to create CrmProductCategory entities within the CleanArchitecture.Blazor 
//       application. It ensures that essential fields are validated correctly, 
//       including maximum lengths and mandatory requirements for required fields.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/crmproductcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator is used to ensure that a CreateCrmProductCategoryCommand meets the required
// validation criteria. It enforces constraints like maximum field lengths and 
// ensures that the Name field is not empty before proceeding with the command execution.

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.Create;

public class CreateCrmProductCategoryCommandValidator : AbstractValidator<CreateCrmProductCategoryCommand>
{
        public CreateCrmProductCategoryCommandValidator()
        {
                RuleFor(v => v.CategoryName).MaximumLength(255); 
    RuleFor(v => v.CrmProductId).NotNull(); 

        }
       
}

