//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       Defines a specification for filtering a SubProduct entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering SubProducts by their ID.
/// </summary>
public class SubProductByIdSpecification : Specification<SubProduct>
{
    public SubProductByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}