//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-13
//     Last Modified: 2025-01-13
//     Description: 
//       Defines the available views for filtering subproducts and provides advanced 
//       filtering options for subproduct lists. This includes pagination and various 
//       filters such as view types and user-specific filters.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.SubProducts.Specifications;

#nullable disable warnings
/// <summary>
/// Specifies the different views available for the SubProduct list.
/// </summary>
public enum SubProductListView
{
    [Description("All")]
    All,
    [Description("My")]
    My,
    [Description("Created Toady")]
    TODAY,
    [Description("Created within the last 30 days")]
    LAST_30_DAYS
}
/// <summary>
/// A class for applying advanced filtering options to SubProduct lists.
/// </summary>
public class SubProductAdvancedFilter: PaginationFilter
{
    public TimeSpan LocalTimezoneOffset { get; set; }
    public SubProductListView ListView { get; set; } = SubProductListView.All;
    public UserProfile? CurrentUser { get; set; }
}