//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2026-04-01
// UpdateContactCommand & handler: updates an existing Contact with cache invalidation and raises ContactUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using System.ComponentModel.DataAnnotations;
using CleanArchitecture.Blazor.Application.Features.Contacts.DTOs;
using CleanArchitecture.Blazor.Application.Features.Contacts.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Contacts.Commands.Update;

public class UpdateContactCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Display(Name ="Id")]
      public int Id { get; set; }
          [Display(Name = "Name")]
    public string Name {get;set;} 
    [Display(Name = "Description")]
    public string? Description {get;set;} 
    [Display(Name = "Email")]
    public string? Email {get;set;} 
    [Display(Name = "Phone number")]
    public string? PhoneNumber {get;set;} 
    [Display(Name = "Country")]
    public string? Country {get;set;} 

      public string CacheKey => ContactCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ContactCacheKey.Tags;

       

}

public class UpdateContactCommandHandler : IRequestHandler<UpdateContactCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IObjectMapper _objectMapper;
    public UpdateContactCommandHandler(
        IObjectMapper objectMapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        _objectMapper = objectMapper;
    }
    public async ValueTask<Result<int>> Handle(UpdateContactCommand request, CancellationToken cancellationToken)
    {
       await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
       var item = await db.Contacts.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"Contact with id: [{request.Id}] not found.");
       }
       item = _objectMapper.Map(request, item);
	    // raise a update domain event
	   item.AddDomainEvent(new ContactUpdatedEvent(item));
       await db.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

