//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Represents a domain event that occurs when a new category is deleted.
//       Used to signal other parts of the system that a new category has been deleted.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

    public class CategoryDeletedEvent : DomainEvent
    {
        public CategoryDeletedEvent(Category item)
        {
            Item = item;
        }

        public Category Item { get; }
    }

