//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2026-03-30
// Domain event for when a new contact is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

public class ContactCreatedEvent : DomainEvent
{
    public ContactCreatedEvent(Contact item)
    {
        Item = item;
    }

    public Contact Item { get; }
}

