//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the Supplier entity 
//       used within the CleanArchitecture.Blazor application. The SupplierDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/supplier
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `SupplierDto` class is used to represent supplier data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing supplier information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

namespace CleanArchitecture.Blazor.Application.Features.Suppliers.DTOs;

[Description("Suppliers")]
public class SupplierDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Name")]
    public string Name {get;set;} 
    [Description("Address")]
    public string? Address {get;set;} 
    [Description("Phone")]
    public string? Phone {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Vat")]
    public string? VAT {get;set;} 
    [Description("Country")]
    public string? Country {get;set;} 
    [Description("Created at")]
    public DateTime CreatedAt {get;set;} 


}

