//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-13
//     Last Modified: 2024-12-13
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       offerlines from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a offerline template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offerline
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportOfferLinesCommand` to import offerlines from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateOfferLinesTemplateCommand` to generate an Excel template for entering offerline data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.OfferLines.DTOs;
using CleanArchitecture.Blazor.Application.Features.OfferLines.Caching;
using CleanArchitecture.Blazor.Application.Features.OfferLines.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.OfferLines.Commands.Import;

    public class ImportOfferLinesCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => OfferLineCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => OfferLineCacheKey.Tags;
        public ImportOfferLinesCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateOfferLinesTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportOfferLinesCommandHandler : 
                 IRequestHandler<CreateOfferLinesTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportOfferLinesCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportOfferLinesCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly OfferLineDto _dto = new();

        public ImportOfferLinesCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportOfferLinesCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportOfferLinesCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, OfferLineDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.OfferId)], (row, item) => item.OfferId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.OfferId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.ItemId)], (row, item) => item.ItemId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ItemId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Quantity)], (row, item) => item.Quantity =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.Quantity)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Discount)], (row, item) => item.Discount =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.Discount)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.LineTotal)], (row, item) => item.LineTotal =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.LineTotal)]]) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
            //        var exists = await _context.OfferLines.AnyAsync(x => x.Name == dto.Name, cancellationToken);
            //        if (!exists)
            //        {
            //            var item = OfferLineMapper.FromDto(dto);
            //            // add create domain events if this entity implement the IHasDomainEvent interface
				        //// item.AddDomainEvent(new OfferLineCreatedEvent(item));
            //            await _context.OfferLines.AddAsync(item, cancellationToken);
            //        }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateOfferLinesTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportOfferLinesCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.OfferId)], 
_localizer[_dto.GetMemberDescription(x=>x.ItemId)], 
_localizer[_dto.GetMemberDescription(x=>x.Quantity)], 
_localizer[_dto.GetMemberDescription(x=>x.Discount)], 
_localizer[_dto.GetMemberDescription(x=>x.LineTotal)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

