////------------------------------------------------------------------------------
//// <auto-generated>
////     This file is part of the CleanArchitecture.Blazor project.
////     Licensed to the .NET Foundation under one or more agreements.
////     The .NET Foundation licenses this file to you under the MIT license.
////     See the LICENSE file in the project root for more information.
////
////     Author: neozhu
////     Created Date: 2025-01-13
////     Last Modified: 2025-01-13
////     Description: 
////       Handles the `SubProductDeletedEvent` which occurs when a new subproduct is deleted.
////       This event handler can be extended to trigger additional actions, such as 
////       sending notifications or updating other systems.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CleanArchitecture.Blazor.Application.Features.SubProducts.EventHandlers;

//    public class SubProductDeletedEventHandler : INotificationHandler<SubProductDeletedEvent>
//    {
//        private readonly ILogger<SubProductDeletedEventHandler> _logger;

//        public SubProductDeletedEventHandler(
//            ILogger<SubProductDeletedEventHandler> logger
//            )
//        {
//            _logger = logger;
//        }
//        public Task Handle(SubProductDeletedEvent notification, CancellationToken cancellationToken)
//        {
//            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
//            return Task.CompletedTask;
//        }
//    }
