//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Defines a query to export crmproductcategory data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified crmproductcategory details.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.DTOs;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Mappers;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Caching;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Queries.Export;

public class ExportCrmProductCategoriesQuery : CrmProductCategoryAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public CrmProductCategoryAdvancedSpecification Specification => new CrmProductCategoryAdvancedSpecification(this);
      public IEnumerable<string>? Tags => CrmProductCategoryCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => CrmProductCategoryCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportCrmProductCategoriesQueryHandler :
         IRequestHandler<ExportCrmProductCategoriesQuery, Result<byte[]>>
{
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportCrmProductCategoriesQueryHandler> _localizer;
        private readonly CrmProductCategoryDto _dto = new();
        public ExportCrmProductCategoriesQueryHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportCrmProductCategoriesQueryHandler> localizer
            )
        {
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportCrmProductCategoriesQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.CrmProductCategories.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo()
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<CrmProductCategoryDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                    {_localizer[_dto.GetMemberDescription(x=>x.CategoryName)],item => item.CategoryName}

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
