//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Defines mapping methods between `CrmProductCategory` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting crmproductcategory data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.Create;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.Update;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class CrmProductCategoryMapper
{
    public static partial CrmProductCategoryDto ToDto(CrmProductCategory source);
    public static partial CrmProductCategory FromDto(CrmProductCategoryDto dto);
    public static partial CrmProductCategory FromEditCommand(AddEditCrmProductCategoryCommand command);
    public static partial CrmProductCategory FromCreateCommand(CreateCrmProductCategoryCommand command);
    public static partial UpdateCrmProductCategoryCommand ToUpdateCommand(CrmProductCategoryDto dto);
    public static partial AddEditCrmProductCategoryCommand CloneFromDto(CrmProductCategoryDto dto);
    public static partial void ApplyChangesFrom(UpdateCrmProductCategoryCommand source, CrmProductCategory target);
    public static partial void ApplyChangesFrom(AddEditCrmProductCategoryCommand source, CrmProductCategory target);
    public static partial IQueryable<CrmProductCategoryDto> ProjectTo(this IQueryable<CrmProductCategory> q);
}

