//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the validation rules for the AddEditSupplierCommand 
//       used to add or edit Supplier entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/supplier
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditSupplierCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.Suppliers.Commands.AddEdit;

public class AddEditSupplierCommandValidator : AbstractValidator<AddEditSupplierCommand>
{
    public AddEditSupplierCommandValidator()
    {
        RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
        RuleFor(v => v.Address).MaximumLength(255); 
        RuleFor(v => v.Phone).MaximumLength(255); 
        RuleFor(v => v.Email).MaximumLength(255); 
        RuleFor(v => v.VAT).MaximumLength(255); 
        RuleFor(v => v.Country).MaximumLength(255); 

     }

}

