//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       Defines a query to export supplier data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified supplier details.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Suppliers.DTOs;
using CleanArchitecture.Blazor.Application.Features.Suppliers.Mappers;
using CleanArchitecture.Blazor.Application.Features.Suppliers.Caching;
using CleanArchitecture.Blazor.Application.Features.Suppliers.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Suppliers.Queries.Export;

public class ExportSuppliersQuery : SupplierAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public SupplierAdvancedSpecification Specification => new SupplierAdvancedSpecification(this);
      public IEnumerable<string>? Tags => SupplierCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => SupplierCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportSuppliersQueryHandler :
         IRequestHandler<ExportSuppliersQuery, Result<byte[]>>
{
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportSuppliersQueryHandler> _localizer;
        private readonly SupplierDto _dto = new();
        public ExportSuppliersQueryHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportSuppliersQueryHandler> localizer
            )
        {
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportSuppliersQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.Suppliers.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo()
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<SupplierDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                    {_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
{_localizer[_dto.GetMemberDescription(x=>x.Address)],item => item.Address}, 
{_localizer[_dto.GetMemberDescription(x=>x.Phone)],item => item.Phone}, 
{_localizer[_dto.GetMemberDescription(x=>x.Email)],item => item.Email}, 
{_localizer[_dto.GetMemberDescription(x=>x.VAT)],item => item.VAT}, 
{_localizer[_dto.GetMemberDescription(x=>x.Country)],item => item.Country}, 
{_localizer[_dto.GetMemberDescription(x=>x.CreatedAt)],item => item.CreatedAt}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
