//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-06
//     Last Modified: 2024-12-06
//     Description: 
//       This file defines the command and its handler for deleting one or more
//       Offer entities from the CleanArchitecture.Blazor application. It
//       implements caching invalidation logic to ensure that data consistency is
//       maintained. Domain events are triggered for deleted entities to support 
//       integration with other parts of the system.
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offer
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to delete multiple Offers from the system by specifying
// their IDs. The handler also raises domain events for each deleted offer to
// notify other bounded contexts and invalidate relevant cache entries.

using CleanArchitecture.Blazor.Application.Features.Offers.Caching;


namespace CleanArchitecture.Blazor.Application.Features.Offers.Commands.Delete;

public class DeleteOfferCommand:  ICacheInvalidatorRequest<Result<int>>
{
  public int[] Id {  get; }
  public string CacheKey => OfferCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => OfferCacheKey.Tags;
  public DeleteOfferCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteOfferCommandHandler : 
             IRequestHandler<DeleteOfferCommand, Result<int>>

{
    private readonly IApplicationDbContext _context;
    public DeleteOfferCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(DeleteOfferCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.Offers.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			//item.AddDomainEvent(new OfferDeletedEvent(item));
            _context.Offers.Remove(item);
        }
        var result = await _context.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(result);
    }

}

