//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       Defines a query for retrieving categorys with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Categories.DTOs;
using CleanArchitecture.Blazor.Application.Features.Categories.Caching;
using CleanArchitecture.Blazor.Application.Features.Categories.Mappers;
using CleanArchitecture.Blazor.Application.Features.Categories.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Categories.Queries.Pagination;

public class CategoriesWithPaginationQuery : CategoryAdvancedFilter, ICacheableRequest<PaginatedData<CategoryDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => CategoryCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => CategoryCacheKey.Tags;
    public CategoryAdvancedSpecification Specification => new CategoryAdvancedSpecification(this);
}
    
public class CategoriesWithPaginationQueryHandler :
         IRequestHandler<CategoriesWithPaginationQuery, PaginatedData<CategoryDto>>
{
        private readonly IApplicationDbContext _context;

        public CategoriesWithPaginationQueryHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<PaginatedData<CategoryDto>> Handle(CategoriesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.Categories.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync(request.Specification, 
                                                                                request.PageNumber, 
                                                                                request.PageSize, 
                                                                                CategoryMapper.ToDto, 
                                                                                cancellationToken);
            return data;
        }
}