//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       This file defines the command for adding or editing a crmproductcategory entity,
//       including validation and mapping operations. It handles domain events
//       and cache invalidation for updated or newly created crmproductcategory.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/crmproductcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to add a new crmproductcategory or edit an existing one.
// It handles caching logic and domain event raising automatically.


using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Caching;
using CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.AddEdit;

public class AddEditCrmProductCategoryCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Category name")]
    public string? CategoryName {get;set;} 
    [Description("Crm product id")]
    public int CrmProductId {get;set;} 


      public string CacheKey => CrmProductCategoryCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => CrmProductCategoryCacheKey.Tags;
}

public class AddEditCrmProductCategoryCommandHandler : IRequestHandler<AddEditCrmProductCategoryCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public AddEditCrmProductCategoryCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(AddEditCrmProductCategoryCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.CrmProductCategories.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"CrmProductCategory with id: [{request.Id}] not found.");
            }
            CrmProductCategoryMapper.ApplyChangesFrom(request,item);
			// raise a update domain event
			item.AddDomainEvent(new CrmProductCategoryUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = CrmProductCategoryMapper.FromEditCommand(request);
            // raise a create domain event
			item.AddDomainEvent(new CrmProductCategoryCreatedEvent(item));
            _context.CrmProductCategories.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

