//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-02
//     Last Modified: 2024-12-02
//     Description: 
//       This file defines the validation rules for the AddEditCrmProductCategoryCommand 
//       used to add or edit CrmProductCategory entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/crmproductcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditCrmProductCategoryCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.CrmProductCategories.Commands.AddEdit;

public class AddEditCrmProductCategoryCommandValidator : AbstractValidator<AddEditCrmProductCategoryCommand>
{
    public AddEditCrmProductCategoryCommandValidator()
    {
                RuleFor(v => v.CategoryName).MaximumLength(255); 
    RuleFor(v => v.CrmProductId).NotNull(); 

     }

}

