name: SonarCloud

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar Analysis
        run: |
          dotnet sonarscanner begin \
          /k:"neozhu" \
          /o:"neo.zhu" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore
        run: dotnet restore CleanArchitecture.Blazor.slnx
      - name: Build
        run: dotnet build CleanArchitecture.Blazor.slnx --configuration Debug --no-restore

      - name: End Sonar Analysis
        run: |
          dotnet sonarscanner end \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"