//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-07
//     Last Modified: 2024-12-07
//     Description: 
//       This file defines the validation rules for the AddEditOfferLineCommand 
//       used to add or edit OfferLine entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/offerline
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditOfferLineCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.OfferLines.Commands.AddEdit;

public class AddEditOfferLineCommandValidator : AbstractValidator<AddEditOfferLineCommand>
{
    public AddEditOfferLineCommandValidator()
    {
                RuleFor(v => v.OfferId).NotNull(); 
    RuleFor(v => v.ItemId).NotNull(); 
    RuleFor(v => v.Quantity).NotNull(); 
    RuleFor(v => v.Discount).NotNull(); 
    RuleFor(v => v.LineTotal).NotNull(); 

     }

}

